# Docker Compose file to set up PostgresSQL and Keycloak services
version: '3.8'

services:
  postgres:
    image: postgres:15              # PostgresSQL particular version or latest
    container_name: postgres_db     # Container name
    restart: always
    ports:
      - "5432:5432"                 # Port mapping host:container
    environment:
      POSTGRES_DB: <DATABASE NAME>            # Database name
      POSTGRES_USER: <DATABASE USERNAME>      # Database username
      POSTGRES_PASSWORD: <DATABASE PASSWORD>  # Database user password
      TZ: Asia/Kolkata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network


  keycloak:
    image: quay.io/keycloak/keycloak:26.4.6     # Keycloak particular version or latest
    container_name: keycloak                    # Container name
    command:
      - start-dev
      - "--import-realm"
    ports:
      - "8989:8080"                             # Port mapping host:container
    depends_on:
      - postgres
    environment:
      KC_DB: postgres                                         # Database type
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak     # Database connection URL [make sure to use the service name as hostname and database should be 'keycloak']
      KC_DB_USERNAME: <DATABASE USERNAME>                          # Database username
      KC_DB_PASSWORD: <DATABASE PASSWORD>                          # Database user password
      KC_BOOTSTRAP_ADMIN_USERNAME: <ADMIN USERNAME>                      # Keycloak admin username
      KC_BOOTSTRAP_ADMIN_PASSWORD: <ADMIN PASSWORD>                      # Keycloak admin password
    networks:
      - postgres_network

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge