# Docker Compose configuration for MongoDB service
version: "3.9"

services:
  # MongoDB Container Configuration
  mongodb:
    image: mongo:7.0                  # MongoDB latest or particular version
    container_name: mongodb           # Container name
    ports:
      - "27017:27017"               # Expose MongoDB port
    environment:
      MONGO_INITDB_ROOT_USERNAME: <DATABASE_USERNAME>     # Database username
      MONGO_INITDB_ROOT_PASSWORD: <DATABASE_PASSWORD>     # Database password
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
